# -*- coding: utf-8 -*-
"""AutoGluon_ImageClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqdhi06_S15lUCfJ7deuRISnHf1jJ-qG

# Import Libraries
"""

pip install --upgrade mxnet-cu100

pip install autogluon

import autogluon as ag
from autogluon import ImageClassification as task

"""# Create AutoGluon Dataset"""

!unzip shop.zip

dataset = task.Dataset('data/train')

test_dataset = task.Dataset('data/test', train=False)

if ag.get_gpu_count() == 0:
    dataset = task.Dataset(name='FashionMNIST')
    test_dataset = task.Dataset(name='FashionMNIST', train=False)

"""# Use AutoGluon to Fit Models"""

classifier = task.fit(dataset,
                      epochs=5,
                      ngpus_per_trial=1,
                      verbose=False)

print('Top-1 val acc: %.3f' % classifier.results['best_reward'])

"""# Predict on a New Image"""

# skip this if training FashionMNIST on CPU.
if ag.get_gpu_count() > 0:
    image = 'data/test/BabyShirt/BabyShirt_323.jpg'
    ind, prob, _ = classifier.predict(image, plot=True)

    print('The input picture is classified as [%s], with probability %.2f.' %
          (dataset.init().classes[ind.asscalar()], prob.asscalar()))

    image = 'data/test/womenchiffontop/womenchiffontop_184.jpg'
    ind, prob, _ = classifier.predict(image, plot=True)

    print('The input picture is classified as [%s], with probability %.2f.' %
          (dataset.init().classes[ind.asscalar()], prob.asscalar()))

"""# Evaluate on Test Datase"""

test_acc = classifier.evaluate(test_dataset)
print('Top-1 test acc: %.3f' % test_acc)